---
- hosts: all
  become: yes # Execute command as root
  vars:
    my_command: "{{ scommand }}"
    banned_words:
      - shutdown
      - poweroff
      - "rm -f" #Remove files
      - kill #Kill process
      - chmod #Changing permission
      - ":(){ :|:& };:" #Fork Bomb

  tasks:
    - name: Check for banned words
      set_fact:
        contains_banned_word: "{{ my_command | regex_search(banned_word) }}"
      loop: "{{ banned_words }}"
      loop_control:
        loop_var: banned_word 

    - name: Fail if banned word is found
      fail:
        #msg: "Banned word '{{ banned_word }}' found in the command '{{ my_command }}'" # issue: {{ banned_word }} is undefined because out of loop
        msg: "Banned word found in the command '{{ my_command }}' - These words '{{ banned_words }}' are not permitted to use!!!"
      when: contains_banned_word != ""

    - name: Execute shell command
      shell: "{{ my_command }}"
      register: output

    - name: Show the output
      debug:
        var: output.stdout_lines